### ISSUE TITLE
Failed ping error running inside container

### ISSUE THREAD

**Issue by rocktz** [hashicorp/memberlist#257]
Hello
I am trying to run 2 instance of my service (on RockyLinux) which uses memberlist for discovery (using DefaultWANConfig() )
The cluster starts up and runs fine. But I am continuously getting the following warnings from memberlist.

Could you please me fix "other probes failed, network may be misconfigured" and "Failed ping" err/warn?

```
calendar-1_1  | 2022-02-08T07:31:04.646Z    2022/02/08 07:31:04 [DEBUG] memberlist: Failed ping: 0843443f-88b1-11ec-a294-0242ac120003 (timeout reached)
calendar-2_1  | 2022-02-08T07:31:04.647Z    2022/02/08 07:31:04 [DEBUG] memberlist: Stream connection from=172.18.0.1:59796
calendar-2_1  | 2022-02-08T07:31:05.237Z    2022/02/08 07:31:05 [DEBUG] memberlist: Failed ping: 07ce372e-88b1-11ec-86f3-0242ac120002 (timeout reached)
calendar-1_1  | 2022-02-08T07:31:05.237Z    2022/02/08 07:31:05 [DEBUG] memberlist: Stream connection from=172.18.0.1:59368
calendar-1_1  | 2022-02-08T07:31:06.646Z    2022/02/08 07:31:06 [WARN] memberlist: Was able to connect to 0843443f-88b1-11ec-a294-0242ac120003 but other probes failed, network may be misconfigured
calendar-2_1  | 2022-02-08T07:31:07.237Z    2022/02/08 07:31:07 [WARN] memberlist: Was able to connect to 07ce372e-88b1-11ec-86f3-0242ac120002 but other probes failed, network may be misconfigured
```

Here is my docker-compose file relevant extract
```
version: "3.9"

networks:
  backend-network:
    driver: bridge

services:
  calendar-1:
    ports:
      - "8101:81"
      - "8001:80"
      - "7777:7777"
      - "9998:9999"
      # command: "/calendar"
    environment:
      - HOST_MACHINE_IP=${HOST_MACHINE_IP}
      - CALENDAR_BOT_GRPC=0.0.0.0:81
      - CALENDAR_BOT_HTTP=0.0.0.0:80
      - CALENDAR_BOT_DATACENTER=lon1
      - CALENDAR_BOT_GRPC_EXPOSED=${HOST_MACHINE_IP}:8101

      - BOTNET_MEMBERLIST_ADVERTISE_ADDRESS=${HOST_MACHINE_IP}:9998
      - BOTNET_MEMBERLIST_BIND_ADDRESS=0.0.0.0:9999
      - BOTNET_MEMBERLIST_KNOWN_NODES=
  calendar-2:
    depends_on:
      - calendar-1
    networks:
      - backend-network
    ports:
      - "8102:81"
      - "8002:80"
      - "9997:9999"
      # command: "/calendar"
    environment:
      - HOST_MACHINE_IP=${HOST_MACHINE_IP}
      - CALENDAR_BOT_GRPC=0.0.0.0:81
      - CALENDAR_BOT_HTTP=0.0.0.0:80
      - CALENDAR_BOT_DATACENTER=lon1
      - CALENDAR_BOT_GRPC_EXPOSED=${HOST_MACHINE_IP}:8102

      - BOTNET_MEMBERLIST_ADVERTISE_ADDRESS=${HOST_MACHINE_IP}:9997
      - BOTNET_MEMBERLIST_BIND_ADDRESS=0.0.0.0:9999
      - BOTNET_MEMBERLIST_KNOWN_NODES=${HOST_MACHINE_IP}:9998
```

where
HOST_MACHINE_IP =public ip of the host
