### ISSUE TITLE
Are there docker ports to open?

### ISSUE THREAD

**Issue by pfortin-urbn** [hashicorp/memberlist#96]
If have memberLists inside docker containers are there ports I need to EXPOSE for memberList to work correctly?  Right now they seems to come up ok but then they both report timeouts and eventually stop talking altogether.

Here is my sample docker-compose file:
```
version: '2'

services:

  app1:
    environment:
      APP_NAME: app1
      CLUSTER_ADDR: app1
      CLUSTER_PORT: 63000
      CLUSTER_MEMBERS:app1:63000
      MAX_CLUSTER_NODES: 50
    hostname: app1
    container_name: app1
    image: myimage
    ports:
      - 8080:8080

  app2:
    environment:
      APP_NAME: app2
      CLUSTER_ADDR: app2
      CLUSTER_PORT: 63001
      CLUSTER_MEMBERS: app1:63000
      MAX_CLUSTER_NODES: 50
    hostname: app2
    container_name: app2
    image: myimage
    ports:
      - 8081:8080
    depends_on:
      - app1
```
